spring.config.import=optional:file:.env[.properties]

spring.application.name=projeto-individual

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
